llm_settings:
  default_model: "gpt-3.5-turbo"
  advanced_model: "gpt-4"

task_allocation:
  simple_tasks: "gpt-3.5-turbo"
  complex_tasks: "gpt-4"

yahoo_finance:
  top_k_results: 10

tavily_search:
  max_results: 4

